# Generated by Django 4.2.16 on 2026-06-06 15:35

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material / Insumo',
                'verbose_name_plural': 'Materiales / Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino_estimada', models.DateField(blank=True, null=True)),
                ('fecha_termino_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente de Firma', 'Pendiente de Firma'), ('Vigente', 'Vigente'), ('Finalizado', 'Finalizado'), ('Rescindido', 'Rescindido')], default='Pendiente de Firma', max_length=25)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.CharField(max_length=50)),
                ('detalle_cambio', models.JSONField()),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('constructora_mandante', models.CharField(max_length=150)),
                ('monto_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino_estimada', models.DateField()),
                ('fecha_termino_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Cerrada', 'Cerrada')], default='Activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel', models.CharField(choices=[('Trabajador', 'Trabajador'), ('Contrato', 'Contrato'), ('Obra', 'Obra')], max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('dias_validez', models.IntegerField(blank=True, help_text='Días de vigencia desde la carga. Vacío = no vence.', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_trabajadores/')),
                ('en_lista_negra', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Drogas', 'Drogas'), ('Alcohol', 'Alcohol'), ('Pelea', 'Pelea'), ('Robo', 'Robo'), ('Ausencia', 'Ausencia'), ('Mala conducta', 'Mala conducta'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_incidente', models.DateField()),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_registro', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strikes', to='core.trabajador')),
            ],
            options={
                'verbose_name': 'Strike',
                'verbose_name_plural': 'Strikes',
                'ordering': ['-fecha_incidente'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO_STOCK', 'Ingreso de Stock'), ('ENTREGA_TERRENO', 'Entrega en Terreno'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_registro', models.CharField(max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='core.catalogomaterial')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_materiales', to='core.obra')),
                ('trabajador_capataz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_recibidos', to='core.trabajador')),
            ],
            options={
                'verbose_name': 'Movimiento de Material',
                'verbose_name_plural': 'Movimientos de Materiales',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='HistorialListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('INGRESO', 'Ingreso a Lista Negra'), ('SALIDA', 'Salida de Lista Negra')], max_length=10)),
                ('motivo', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_registro', models.CharField(max_length=100)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_lista_negra', to='core.trabajador')),
            ],
            options={
                'verbose_name': 'Historial Lista Negra',
                'verbose_name_plural': 'Historial Lista Negra',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(blank=True, max_length=12, null=True)),
                ('archivo', models.FileField(upload_to=core.models.documento_upload_path)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('usuario_carga', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.contrato')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.obra')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.especialidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.obra'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.trabajador'),
        ),
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_cierre', models.CharField(max_length=100)),
                ('archivo_consolidado', models.FileField(blank=True, null=True, upload_to='cierres_mensuales/')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_mensuales', to='core.obra')),
            ],
            options={
                'verbose_name': 'Cierre Mensual',
                'verbose_name_plural': 'Cierres Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('obra', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='BodegaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodega_items', to='core.catalogomaterial')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodega_items', to='core.obra')),
            ],
            options={
                'verbose_name': 'Bodega Obra',
                'verbose_name_plural': 'Bodega Obras',
                'unique_together': {('obra', 'material')},
            },
        ),
    ]
