# Generated by Django 4.2.16 on 2026-06-06 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('Plazo Fijo', 'Plazo Fijo'), ('Por Obra o Faena', 'Por Obra o Faena'), ('Indefinido', 'Indefinido')], default='Plazo Fijo', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Pendiente de Firma', 'Pendiente de Firma'), ('Vigente', 'Vigente'), ('Finalizado', 'Finalizado'), ('Rescindido', 'Rescindido'), ('Trasladado', 'Trasladado')], default='Pendiente de Firma', max_length=25),
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_traslado', models.CharField(choices=[('SIN_FINIQUITO', 'Traslado sin Finiquito (Contrato Continúa)'), ('CON_FINIQUITO', 'Traslado con Finiquito (Nuevo Contrato)')], max_length=20)),
                ('finiquito_pendiente', models.BooleanField(default=False)),
                ('fecha_traslado', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('usuario_registro', models.CharField(max_length=150)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('contrato_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_como_destino', to='core.contrato')),
                ('contrato_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_como_origen', to='core.contrato')),
                ('obra_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='core.obra')),
                ('obra_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='core.obra')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='core.trabajador')),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'ordering': ['-creado_el'],
            },
        ),
    ]
