# Generated by Django 4.2.16 on 2026-06-06 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contrato_tipo_contrato_alter_contrato_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut_empresa', models.CharField(max_length=20)),
                ('giro', models.CharField(blank=True, default='Constructora', max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('nombre_representante', models.CharField(max_length=150)),
                ('rut_representante', models.CharField(max_length=20)),
                ('cargo_representante', models.CharField(blank=True, default='Representante Legal', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato_trabajo', 'Contrato de Trabajo'), ('anexo_contrato', 'Anexo Contrato de Trabajo'), ('finiquito', 'Finiquito de Trabajo'), ('pacto_horas_extras', 'Pacto Horas Extraordinarias'), ('acta_epp', 'Acta Entrega EPP'), ('acta_reglamento', 'Acta Entrega Reglamento Interno')], max_length=30)),
                ('datos', models.JSONField(default=dict)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='core.contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='core.configempresa')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='core.obra')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='core.trabajador')),
            ],
            options={
                'verbose_name': 'Documento Generado',
                'verbose_name_plural': 'Documentos Generados',
                'ordering': ['-creado_el'],
            },
        ),
    ]
