# Generated by Django 4.2.16 on 2026-06-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configempresa_documentogenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='tipo_identificacion',
            field=models.CharField(choices=[('RUT', 'RUT Chileno'), ('PASAPORTE', 'Pasaporte'), ('DNI', 'DNI / Cédula Extranjera')], default='RUT', max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
