# Generated by Django 4.2.16 on 2026-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipo_identificacion_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Conviviente Civil', 'Conviviente Civil'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Chilena', max_length=50),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='prevision',
            field=models.CharField(blank=True, help_text='AFP o INP', max_length=100),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='procedencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='salud',
            field=models.CharField(blank=True, help_text='FONASA o Isapre', max_length=100),
        ),
    ]
