# Generated by Django 4.2.16 on 2026-06-07 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campos_personales_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección / Ubicación de la Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='core.configempresa', verbose_name='Empresa Contratista'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='constructora_mandante',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
