# Generated by Django 4.2.16 on 2026-06-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_obra_empresa_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configempresa',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
