# Generated by Django 5.2.7 on 2026-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogomaterial',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Material / Insumo', 'verbose_name_plural': 'Materiales / Insumos'},
        ),
        migrations.AddField(
            model_name='catalogomaterial',
            name='categoria',
            field=models.CharField(choices=[('EPP', 'EPP / Protección Personal'), ('ENFIERRADURA', 'Enfierradura'), ('CONSTRUCCION', 'Materiales de Construcción'), ('HERRAMIENTAS', 'Herramientas'), ('ELECTRICO', 'Materiales Eléctricos'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogomaterial',
            name='stock_global',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogomaterial',
            name='unidad_medida',
            field=models.CharField(choices=[('unid', 'Unidad'), ('par', 'Par'), ('kg', 'Kilogramo'), ('lts', 'Litros'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('rollo', 'Rollo'), ('caja', 'Caja'), ('saco', 'Saco'), ('gl', 'Galón')], default='unid', max_length=10),
        ),
    ]
