# Generated by Django 5.2.7 on 2026-06-07 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_catalogo_material_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmaterial',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_materiales', to='core.obra'),
        ),
    ]
