# Generated by Django 5.2.7 on 2026-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historial_obra_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomaterial',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
