# Generated by Django 5.2.7 on 2026-06-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_material_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierremensual',
            options={'ordering': ['-anio', '-mes', '-fecha_cierre'], 'verbose_name': 'Cierre Mensual', 'verbose_name_plural': 'Cierres Mensuales'},
        ),
        migrations.AlterUniqueTogether(
            name='cierremensual',
            unique_together=set(),
        ),
    ]
