# Generated by Django 5.2.7 on 2026-06-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_cierremensual_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierremensual',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
