# Generated by Django 5.2.7 on 2026-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_cierre_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]
