# Generated by Django 5.2.7 on 2026-06-08 17:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_obra_archivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmaterial',
            name='receptor_libre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cierremensual',
            name='archivo_consolidado',
            field=models.FileField(blank=True, null=True, upload_to=core.models.cierre_upload_path),
        ),
    ]
