# Generated by Django 5.2.7 on 2026-06-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_licencia_historial_config_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='motivo_termino',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_termino',
            field=models.CharField(blank=True, choices=[('', '— Sin término —'), ('Renuncia voluntaria', 'Renuncia voluntaria'), ('Despido por necesidades de la empresa', 'Despido por necesidades de la empresa'), ('Despido por incumplimiento grave', 'Despido por incumplimiento grave'), ('Mutuo acuerdo', 'Mutuo acuerdo'), ('Vencimiento plazo', 'Vencimiento plazo'), ('Término de obra o faena', 'Término de obra o faena'), ('Fallecimiento', 'Fallecimiento'), ('Invalidez', 'Invalidez'), ('Otro', 'Otro')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='tasa_afp_empleado',
            field=models.DecimalField(decimal_places=2, default=10.58, help_text='% cotización obligatoria AFP (varía por AFP)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='tasa_cesantia_empleado_indefinido',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='% seguro cesantía empleado (indefinido)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='tasa_cesantia_empleado_plazo_fijo',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='% seguro cesantía empleado (plazo fijo)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='tasa_cesantia_empleador',
            field=models.DecimalField(decimal_places=2, default=2.4, help_text='% seguro cesantía empleador', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='tasa_mutual_accidentes',
            field=models.DecimalField(decimal_places=2, default=0.93, help_text='% seguro accidentes del trabajo (varía por empresa)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configremuneraciones',
            name='tasa_salud_empleado',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='% cotización salud obligatoria', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contratohistorial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licenciamedica',
            name='empresa_pago_3_dias',
            field=models.BooleanField(default=False, help_text='Para tipo 1: ¿la empresa pagó los 3 primeros días?'),
        ),
        migrations.AlterField(
            model_name='licenciamedica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licenciamedica',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencias', to='core.trabajador'),
        ),
    ]
