# Generated by Django 5.2.7 on 2026-06-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contrato_tipo_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentogenerado',
            name='motivo_baja',
            field=models.TextField(blank=True, default='', help_text='Motivo por el cual se reemplazó o anuló este documento (trazabilidad de auditoría).'),
        ),
        migrations.AddField(
            model_name='licenciamedica',
            name='institucion_nombre',
            field=models.CharField(blank=True, default='', help_text='Hospital, clínica, mutual o mutualidad que emitió la licencia. Ej: Mutual de Seguridad, Hospital Las Higueras.', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='cierremensual',
            unique_together={('obra', 'mes', 'anio')},
        ),
    ]
