# Generated by Django 5.2.7 on 2026-06-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_documento_paper_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.especialidad'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente de Firma', 'Pendiente de Firma'), ('Vigente', 'Vigente'), ('En Licencia', 'En Licencia'), ('Reactivado', 'Reactivado'), ('Finalizado', 'Finalizado'), ('Finiquitado', 'Finiquitado'), ('Rescindido', 'Rescindido'), ('Trasladado', 'Trasladado')], default='Pendiente de Firma', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='sueldo_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
