# Generated by Django 5.2.7 on 2026-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_finiquito_legalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='trabajador_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
